In [7]:
import requests
import pandas as pd

my_key = "dpd-18545c69-0bbe8c1e0c8abc6954ae9fba80d70c40b363199406e6d75dd2f288a7a66f3cf1"
def get_financials(stockCode, indicatorName, apiKey, consolidated=True, ttm=True):
    
	if consolidated:
		if ttm:
			url = f"https://api.dapada.io/company/getConsolidatedFinancialDataByTTM?indicatorName={indicatorName}&stockCode={stockCode}"
		else:
			url = f"https://api.dapada.io/company/getConsolidatedFinancialDataByCUR?indicatorName={indicatorName}&stockCode={stockCode}"
	else:
		if ttm:
			url = f"https://api.dapada.io/company/getSeparatedFinancialDataByTTM?indicatorName={indicatorName}&stockCode={stockCode}"
		else:
			url = f"https://api.dapada.io/company/getSeparatedFinancialDataByCUR?indicatorName={indicatorName}&stockCode={stockCode}"

	headers = {"Authorization" : f"{apiKey}"}
	response = requests.get(url, headers = headers)
	result = response.json()
	return pd.DataFrame(result)

df_ttm_consolidated = get_financials(stockCode='005930',
									 indicatorName='매출액',
									 apiKey = my_key,
									 consolidated = True,
									 ttm =True)

df_ttm_consolidated

             value  quarter
0  261620131000000  2023-Q3
1  270997159000000  2023-Q2
2  288195233000000  2023-Q1
3  302231360000000  2022-Q4
4  308332309000000  2022-Q3
5  305529816000000  2022-Q2
6  291997794000000  2022-Q1

In [8]:
df_cur_consolidated = get_financials(stockCode='005930',
									 indicatorName='매출액',
									 apiKey = my_key,
									 consolidated = True,
									 ttm =False)

df_ttm_consolidated

             value  quarter
0  261620131000000  2023-Q3
1  270997159000000  2023-Q2
2  288195233000000  2023-Q1
3  302231360000000  2022-Q4
4  308332309000000  2022-Q3
5  305529816000000  2022-Q2
6  291997794000000  2022-Q1