In [2]:
import pandas as pd

In [3]:
dict_data = {
	'c0' : [1, 2, 3],
	'c1' : [4, 5, 6],
	'c2' : [7, 8, 9],
	'c3' : [10, 11, 12],
	'c4' : [13, 14, 15]
}

df = pd.DataFrame(dict_data)
print(type(df))
print(df)

<class 'pandas.DataFrame'>
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [4]:
# pandas.DataFrame(2차원배열,
#                  index = 행 인덱스 배열,
#                  columns = 열 이름 배열)

arr = [
    [15, "남", "덕영중"],
    [17, "여", "수리중"],
]

df = pd.DataFrame(arr, index=['준서', '예은'], columns=['나이', '성별', '학교'])

print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [5]:
print(df.index)
print(list(df.index))
print(df.columns)
print(list(df.columns))
print(tuple(df.columns))

Index(['준서', '예은'], dtype='str')
['준서', '예은']
Index(['나이', '성별', '학교'], dtype='str')
['나이', '성별', '학교']
('나이', '성별', '학교')

In [6]:
# 행 인덱스 변경
# DataFrame객체.index = 행인덱스배열
# DataFrame객체.columns = 열인덱스배열

print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [7]:
df.index = ['학생1', '학생2']
df.columns = ['연령', '남녀', '소속']

print(df)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [8]:
# 행 인덱스 변경 : DataFrame 객체.rename(index={기존 인덱스:새 인덱스, ...})
# 열 이름 변경 : DataFrame 객체.rename(columns={기존 이름:새 이름, ...})

import pandas as pd

matrix = [
    [15, '남', '덕영중'],
    [17, '여', '수리중'],
]

df = pd.DataFrame(matrix,  index = ['준서', '예은'], columns = ['나이', '성별', '학교'])
df #print 안쓰고 그냥 출력 하면 이쁘게 나옴. 근데 이건 jupyter notebook 기능

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [9]:
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [10]:
df.rename(columns={
    "나이" : "연령",
    "성별" : "남녀",
    "학교" : "소속"
    })  # 여기까지만 하면 바뀐상태로 나오긴 한데, 재할당해야함. 재할당 안하면 나중에 df 했을때 다시 원래대로 돌아감

df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [11]:
df.rename(index={
    "준서" : "학생1",
    "예은" : "학생2"
})
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [12]:
# 행/열 삭제
# 행 삭제 : DataFrame객체.drop(행인덱스 또는 배열, axis=0 또는 axis="index")
# 열 삭제 : DataFrame객체.drop(열이름 또는 배열, axis=1 또는 axis="columns")

import pandas as pd

exam_data = {
    "수학" : [ 90, 80, 70],
    "영어" : [ 98, 89, 95],
    "음악" : [ 85, 95, 100],
    "체육" : [ 100, 90, 90]
}

df = pd.DataFrame(exam_data, index = ['서준', '우현', '인아'])
print(df)
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [13]:
df2 = df.copy()
df2 = df2.drop('우현')
print(df2)

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [14]:
df3 = df.copy()
print(df3)
print("=========="*4)
df3 = df.drop(['우현', '인아'], axis=0)
# df3 = df.drop('우현', '인아', axis=0) #반드시 리스트로 해야함. 이런식으로 하면 안됨!

print(df3)

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
========================================
    수학  영어  음악   체육
서준  90  98  85  100

In [15]:
df4 = df.copy()
df4 = df.drop(['우현', '인아'], axis='index')
print(df4)
df4

    수학  영어  음악   체육
서준  90  98  85  100

    수학  영어  음악   체육
서준  90  98  85  100

In [16]:
df5 = df.copy()
df5 = df.drop(index=['우현'])
print(df5)
df5

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [17]:
import pandas as pd

exam_data = {
    "수학" : [ 90, 80, 70],
    "영어" : [ 98, 89, 95],
    "음악" : [ 85, 95, 100],
    "체육" : [ 100, 90, 90]
}

df = pd.DataFrame(exam_data, index = ['서준', '우현', '인아'])
print(df)

print("="*20)

df2 = df.copy()
df2 = df.drop('수학', axis=1)
print(df2)

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
====================
    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [18]:
df3 = df.copy()
df3 = df3.drop(['영어', '음악'], axis=1)
print(df3)
df3

    수학   체육
서준  90  100
우현  80   90
인아  70   90

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [19]:
df4 = df.copy()
df4 = df4.drop(['영어', '음악'], axis = 'columns')
print(df4)
df4

    수학   체육
서준  90  100
우현  80   90
인아  70   90

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [20]:
df5=df.copy()
df5 = df5.drop(columns=['수학'])
print(df5)
df5

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [21]:
# 행선택
import pandas as pd

exam_data = {
    "수학" : [ 90, 80, 70],
    "영어" : [ 98, 89, 95],
    "음악" : [ 85, 95, 100],
    "체육" : [ 100, 90, 90]
}

df = pd.DataFrame(exam_data, index = ['서준', '우현', '인아'])
print(df)
print("")

label1 = df.loc['서준']
position1 = df.iloc[0]
print(label1)
print(type(label1))
print("")
print(position1)
print(type(position1))

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>

In [22]:
label2 = df.loc[['서준', '우현']]
position2 = df.iloc[[0,1]]

print(label2)
print(type(label2))
print("")
print(position2)
print(type(position2))

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90
<class 'pandas.DataFrame'>

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90
<class 'pandas.DataFrame'>

In [23]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [24]:
# lable3 = df.loc[["서준"]] # 하나만 가져와도 dataframe임

# print(lable3)
# print(type(lable3))

In [25]:
label3 = df.loc["서준" : '우현']
print(label3)

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [26]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [27]:
position3 = df.iloc[0:2]
print(position3)

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [28]:
# 열1개 선택 : DataFrame 객체["열이름"] 또는 DataFrame 객체.열이름

exam_data = {
    "이름" : ["서준", "우현", "인아"],
    "수학" : [ 90, 80, 70],
    "영어" : [ 98, 89, 95],
    "음악" : [ 85, 95, 100],
    "체육" : [ 100, 90, 90]
}

df = pd.DataFrame(exam_data)
print(df)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [29]:
math1 = df['수학']
print(math1)
print(type(math1))

0    90
1    80
2    70
Name: 수학, dtype: int64
<class 'pandas.Series'>

In [30]:
english = df.영어
print(english)
print(type(english))

0    98
1    89
2    95
Name: 영어, dtype: int64
<class 'pandas.Series'>

In [31]:
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [32]:
music_gym = df[['음악', '체육']]
print(music_gym)
print(type(music_gym))

    음악   체육
0   85  100
1   95   90
2  100   90
<class 'pandas.DataFrame'>

In [33]:
math2 = df[['수학']]
print(math2)
print(type(math2))

   수학
0  90
1  80
2  70
<class 'pandas.DataFrame'>

In [34]:
# 범위슬라이싱 : DataFrame객체.iloc[ 시작인덱스:끝인덱스:슬라이싱간격]
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [35]:
df.iloc[ : : 2]

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
2  인아  70  95  100   90

In [36]:
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [39]:
exam_data = {
    "이름" : ["서준", "우현", "인아"],
    "수학" : [ 90, 80, 70],
    "영어" : [ 98, 89, 95],
    "음악" : [ 85, 95, 100],
    "체육" : [ 100, 90, 90]
}

df = pd.DataFrame(exam_data)

df = df.set_index('이름')
print(df)

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [41]:
a = df.loc["서준", "음악"]
print(a)
b=df.iloc[0,2]
print(b)

85
85

In [43]:
c = df.loc['서준', ['음악', '체육']]
print(c)
d = df.iloc[0, [2, 3]]
print(d)
e = df.loc['서준', '음악':'체육']
print(e)
f = df.iloc[0, 2:]
print(f)

음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64

In [45]:
g = df.loc[['서준', '우현'], ['음악', '체육']]
print(g)
h = df.iloc[[0,1], [2,3]]
print(h)
i = df.loc['서준':'우현', '음악':'체육']
print(i)
j = df.iloc[0:2, 2:]
print(j)

    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90

In [47]:
#열 추가
# 열추가 : DataFrame객체["추가하려는 열 이름"] = 데이터값

exam_data = {
    "이름" : ["서준", "우현", "인아"],
    "수학" : [ 90, 80, 70],
    "영어" : [ 98, 89, 95],
    "음악" : [ 85, 95, 100],
    "체육" : [ 100, 90, 90]
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [ ]:
# df['국어']  <-- 이렇게 없는 값을 가져오려 하면 에러남
df['국어'] = 80 # <-- 이렇게 추가는 가능
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  인아  70  95  100   90  80

In [52]:
df['미술'] = [80, 90, 100]
df

   이름  수학  영어   음악   체육  국어   미술
0  서준  90  98   85  100  80   80
1  우현  80  89   95   90  80   90
2  인아  70  95  100   90  80  100

In [53]:
#행추가
# 행추가 : DataFrame객체.loc["새로운행이름"] = 데이터값(또는 배열)
exam_data = {
    "이름" : ["서준", "우현", "인아"],
    "수학" : [ 90, 80, 70],
    "영어" : [ 98, 89, 95],
    "음악" : [ 85, 95, 100],
    "체육" : [ 100, 90, 90]
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [56]:
print(df.loc[0])
print(df.iloc[0])

이름     서준
수학     90
영어     98
음악     85
체육    100
Name: 0, dtype: object
이름     서준
수학     90
영어     98
음악     85
체육    100
Name: 0, dtype: object

In [ ]:
#둘의 결과는 다름!
print(df.loc[0:2])
print(df.iloc[0:2])

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
   이름  수학  영어  음악   체육
0  서준  90  98  85  100
1  우현  80  89  95   90

In [60]:
df.loc[3] = 0
print(df)
print("")

df.loc[4] = ['동규', 90, 80, 70, 60]
print(df)
print("")

df.loc['행5'] = df.loc[3]
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0
4  동규  90  80   70   60

    이름  수학  영어   음악   체육
0   서준  90  98   85  100
1   우현  80  89   95   90
2   인아  70  95  100   90
3    0   0   0    0    0
4   동규  90  80   70   60
행5   0   0   0    0    0

In [61]:
# 원소 값 변경
import pandas as pd

exam_data = {
    "이름" : ["서준", "우현", "인아"],
    "수학" : [ 90, 80, 70],
    "영어" : [ 98, 89, 95],
    "음악" : [ 85, 95, 100],
    "체육" : [ 100, 90, 90]
}

df = pd.DataFrame(exam_data)

df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [62]:
df = df.set_index('이름')
print(df)

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [64]:
df.iloc[0, 3] = 80
print(df)

    수학  영어   음악  체육
이름
서준  90  98   85  80
우현  80  89   95  90
인아  70  95  100  90

In [68]:
df.loc['서준', '체육'] = 90
print(df)

    수학  영어   음악  체육
이름
서준  90  98   85  90
우현  80  89   95  90
인아  70  95  100  90

In [69]:
df.loc['서준', ['음악', '체육']] = 50
print(df)

df.loc['서준', ['음악', '체육']] = 100, 50
print(df)

    수학  영어   음악  체육
이름
서준  90  98   50  50
우현  80  89   95  90
인아  70  95  100  90
    수학  영어   음악  체육
이름
서준  90  98  100  50
우현  80  89   95  90
인아  70  95  100  90

In [70]:
# 행, 열의 위치 바꾸기
# 행, 열 바꾸기 : DataFrame객체.transpose() 또는 DataFrame객체.T

import pandas as pd

exam_data = {
    "이름" : ["서준", "우현", "인아"],
    "수학" : [ 90, 80, 70],
    "영어" : [ 98, 89, 95],
    "음악" : [ 85, 95, 100],
    "체육" : [ 100, 90, 90]
}

df = pd.DataFrame(exam_data)

df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [74]:
df = df.transpose()

df

      0   1    2
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90

In [75]:
df = df.T
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90