In [1]:
#구간분할

import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./data/auto-mpg.csv', header=None)

df.columns = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'name']

In [3]:
df['horsepower'] = df['horsepower'].replace('?', np.nan)
df = df.dropna(subset=['horsepower'], axis=0)
df['horsepower'] = df['horsepower'].astype('float')

In [5]:
count, bin_dividers = np.histogram(df['horsepower'], bins=3)

print(bin_dividers)

[ 46.         107.33333333 168.66666667 230.        ]

In [7]:
bin_names = ['저출력', '보통출력', '고출력']

df['hp_bin'] = pd.cut(
    x=df['horsepower'],
    bins=bin_dividers,
    labels = bin_names,
    include_lowest=True)

df[['horsepower', 'hp_bin']].head(15)

    horsepower hp_bin
0        130.0   보통출력
1        165.0   보통출력
2        150.0   보통출력
3        150.0   보통출력
4        140.0   보통출력
5        198.0    고출력
6        220.0    고출력
7        215.0    고출력
8        225.0    고출력
9        190.0    고출력
10       170.0    고출력
11       160.0   보통출력
12       150.0   보통출력
13       225.0    고출력
14        95.0    저출력

In [10]:
# 더미변수

horsepower_dummies = pd.get_dummies(df["hp_bin"])
horsepower_dummies.head(10)

     저출력   보통출력    고출력
0  False   True  False
1  False   True  False
2  False   True  False
3  False   True  False
4  False   True  False
5  False  False   True
6  False  False   True
7  False  False   True
8  False  False   True
9  False  False   True

In [11]:
horsepower_dummies_float = pd.get_dummies(df["hp_bin"], dtype=float)
horsepower_dummies_float.head()

   저출력  보통출력  고출력
0  0.0   1.0  0.0
1  0.0   1.0  0.0
2  0.0   1.0  0.0
3  0.0   1.0  0.0
4  0.0   1.0  0.0

In [12]:
horsepower_dummies_drop = pd.get_dummies(df['hp_bin'], dtype=float, drop_first=True)
horsepower_dummies_drop.head()

   보통출력  고출력
0   1.0  0.0
1   1.0  0.0
2   1.0  0.0
3   1.0  0.0
4   1.0  0.0

In [14]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
onehot_encoder = preprocessing.OneHotEncoder()

onehot_labeled = label_encoder.fit_transform(df["hp_bin"].head(15))

print(onehot_labeled)
print(type(onehot_labeled))

[1 1 1 1 1 0 0 0 0 0 0 1 1 0 2]
<class 'numpy.ndarray'>

In [16]:
onehot_reshaped = onehot_labeled.reshape(len(onehot_labeled), 1)
print(onehot_reshaped)
print(type(onehot_reshaped))

[[1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [2]]
<class 'numpy.ndarray'>

In [17]:
onehot_fitted = onehot_encoder.fit_transform(onehot_reshaped)
print(onehot_fitted)
print(type(onehot_fitted))

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 15 stored elements and shape (15, 3)>
  Coords	Values
  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 1)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 1)	1.0
  (12, 1)	1.0
  (13, 0)	1.0
  (14, 2)	1.0
<class 'scipy.sparse._csr.csr_matrix'>